Added check parameter consistency.

diff --git a/bin/git-team b/bin/git-team
--- a/bin/git-team
+++ b/bin/git-team
@@ -26,7 +26,7 @@
 #   - `-c` repository category to process - team|shallow - default to `shallow`
 #   - `-b` branch to apply operation onto - no effect on `pull` operation - default to `main`
 #   - `-f` fall back branch if `branch` doesn't exists - no effect on `pull` operation - default to `main`
-#   - `-s` shallow repositories to process
+#   - `-s` shallow repositories to process / ignore (for git-config parameters)
 #   - `-p` production repositories to process
 #   - `-p|-s` can be either of:
 #       - "Ensembl" xxx repo name - ex: ensembl-production
@@ -34,8 +34,11 @@
 #       - "File path" containing a list of repositories to process - one per line
 
 function usage {
-  echo "Usage: $0 [-o git_operation] [-c shallow|team] [-b branch] [-f default_branch] [-t target_dir] [-s shallow_file|repo|config] [-p team_file|repo|team_config]"
+  echo "---------------------------------------"
+  echo "Usage: $0 [-o git_operation (pull)] [-c shallow|team (shallow)] [-b branch] [-f default_branch] [-t target_dir] [-r file|repo|git-config]"
   echo "Example: $0 -o clone -c shallow -s ~/shallow.repo"
+  echo "Example: $0 -o pull -c team -s ~/shallow.repo -p ~/.prod.repo"
+  echo "---------------------------------------"
   exit 1
 }
 shallow=()
@@ -52,25 +55,43 @@ while getopts 'o:c:s:p:t:b:f:d' opt; do
     *) usage ;;
   esac
 done
-# repo configuration with file
-if [[ -f "$shallow" ]]; then
-  shallow=(`cat $shallow`)
-fi
-if [[ -f "$prod" ]]; then
-  prod=(`cat $prod`)
-fi
 
-# Ensembl shallow repositories (depth=1)
+# settings defaults
+op=${op:-'pull'}
 branch=${branch:-"main"}
 default_branch=${default_branch:-"main"}
+category=${category:-'shallow'}
 target_dir=${target_dir:-"${PWD}"}
+# checking params
+if [[ ! $category =~ shallow|team ]]; then
+  echo 'Category is "shallow" or "team"' >&2
+  usage
+fi
+if [[ "$category" == "shallow" ]]; then
+  if [[ -z "$shallow" ]]; then
+    # category shallow need shallow param
+    echo 'Missing -s for category "shallow"' >&2
+    usage
+  fi
+elif [[ -z "$prod" ]] || [[ -z "$shallow" ]]; then
+  # category
+  echo 'Missing -p and/or s for category "team"' >&2
+  usage
+fi
 
 if [[ ! -d $target_dir ]]; then
   mkdir -p $target_dir
 fi
+# repo configuration with files
+if [[ -f "$shallow" ]]; then
+  echo "Loading shallow config from file `realpath $shallow`"
+  shallow=(`cat $(realpath $shallow)`)
+fi
+if [[ -f "$prod" ]]; then
+  echo "Loading team config from file `realpath $prod`"
+  prod=(`cat $(realpath $prod)`)
+fi
 
-category=${category:-'shallow'}
-op=${op:-'pull'}
 ignore=( "${shallow[@]/#/--ignore_module }" )
 dir=$(pwd)
 cd ${target_dir}
